export {default as Home} from './Home/Home'
export {default as Studio} from './Studio/Studio'
export {default as AlgoritmJob} from './Algoritm-job/Algoritm-job'
export {default as ServicesDetailCard} from './Services-detail-card/Services-detail-card'
export {default as ContactPage} from './Contact-page/Contact-page'
export {default as Blog} from './Blog/Blog'
export {default as BlogChild} from './Blog-child/Blog-child'
export {default as ServicesChildPage} from './Services-child-page/Services-child-page'
export {default as Vacancy} from './Vacancy/Vacansy'

export {default as ServicesPage} from './Services-page/Services-page'